#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# routes register et login
register:
  path: /register
  controller: App\Controller\RegistrationController::register

login:
  path: /login
  controller: App\Controller\SecurityController::login

# routes accueil

home:
  path: /home
  controller: App\Controller\HomeController::index

# routes truck

truck:
  path: /truck
  controller: App\Controller\TruckController::index

create:
  path: /truck/create
  controller: App\Controller\TruckController::create

mytruck:
  path: /truck/mytruck/{$id}
  controller: App\Controller\TruckController::mytruck

menu:
  path: /truck/menu
  controller: App\Controller\TruckController::menu

update:
  path: /truck/update/{id}
  controller: App\Controller\TruckController::update

createproduct:
  path: /truck/createproduct
  controller: App\Controller\TruckController::createproduct

updateproduct:
  path: /truck/updateproduct/{id}
  controller: App\Controller\TruckController::updateproduct

deleteproduct:
  path: /truck/deleteproduct/{id}
  controller: App\Controller\TruckController::deleteproduct
